### Матричные факторизации

В данной работе вам предстоит познакомиться с практической стороной матричных разложений.
Работа поделена на 4 задания:
1. Вам необходимо реализовать SVD разложения используя SGD на explicit данных
2. Вам необходимо реализовать матричное разложения используя ALS на implicit данных
3. Вам необходимо реализовать матричное разложения используя BPR(pair-wise loss) на implicit данных
4. Вам необходимо реализовать матричное разложения используя WARP(list-wise loss) на implicit данных

Мягкий дедлайн 28 Сентября (пишутся замечания, выставляется оценка, есть возможность исправить до жесткого дедлайна)

Жесткий дедлайн 5 Октября (Итоговая проверка)

In [1]:
import implicit
import pandas as pd
import time
import numpy as np
import scipy.sparse as sp
from copy import deepcopy as dp
from tqdm import tqdm
from lightfm.datasets import fetch_movielens

/Users/sergekulesh/opt/miniconda3/lib/python3.7/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '


В данной работе мы будем работать с explicit датасетом movieLens, в котором представленны пары user_id movie_id и rating выставленный пользователем фильму

Скачать датасет можно по ссылке https://grouplens.org/datasets/movielens/1m/

In [2]:
ratings = pd.read_csv('ratings.dat', delimiter='::', header=None, 
        names=['user_id', 'movie_id', 'rating', 'timestamp'], 
        usecols=['user_id', 'movie_id', 'rating'], engine='python')

In [3]:
movie_info = pd.read_csv('movies.dat', delimiter='::', header=None, 
        names=['movie_id', 'name', 'category'], engine='python')

Explicit данные

In [4]:
ratings.head(10)

user_id  movie_id  rating
0        1      1193       5
1        1       661       3
2        1       914       3
3        1      3408       4
4        1      2355       5
5        1      1197       3
6        1      1287       5
7        1      2804       5
8        1       594       4
9        1       919       4

Для того, чтобы преобразовать текущий датасет в Implicit, давайте считать что позитивная оценка это оценка >=4

In [5]:
implicit_ratings = ratings.loc[(ratings['rating'] >= 4)]

In [6]:
implicit_ratings.head(10)

user_id  movie_id  rating
0         1      1193       5
3         1      3408       4
4         1      2355       5
6         1      1287       5
7         1      2804       5
8         1       594       4
9         1       919       4
10        1       595       5
11        1       938       4
12        1      2398       4

Удобнее работать с sparse матричками, давайте преобразуем DataFrame в CSR матрицы

In [7]:
users = implicit_ratings["user_id"]
movies = implicit_ratings["movie_id"]
user_item = sp.coo_matrix((np.ones_like(users), (users, movies)))
user_item_t_csr = user_item.T.tocsr()
user_item_csr = user_item.tocsr()

В качестве примера воспользуемся ALS разложением из библиотеки implicit

Зададим размерность латентного пространства равным 64, это же определяет размер user/item эмбедингов

In [8]:
model = implicit.als.AlternatingLeastSquares(factors=64, iterations=100, calculate_training_loss=True)

В качестве loss здесь всеми любимый RMSE

In [9]:
model.fit(user_item_t_csr)

Построим похожие фильмы по 1 movie_id = Истории игрушек

In [10]:
movie_info.head(5)

movie_id                                name                      category
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [11]:
get_similars = lambda item_id, model : [movie_info[movie_info["movie_id"] == x[0]]["name"].to_string() 
                                        for x in model.similar_items(item_id)]

Как мы видим, симилары действительно оказались симиларами.

Качество симиларов часто является хорошим способом проверить качество алгоритмов.

P.S. Если хочется поглубже разобраться в том как разные алгоритмы формируют разные латентные пространства, рекомендую загружать полученные вектора в tensorBoard и смотреть на сформированное пространство

In [12]:
get_similars(1, model)

['0    Toy Story (1995)',
 '3045    Toy Story 2 (1999)',
 "2286    Bug's Life, A (1998)",
 '33    Babe (1995)',
 '584    Aladdin (1992)',
 '2315    Babe: Pig in the City (1998)',
 '360    Lion King, The (1994)',
 '1526    Hercules (1997)',
 '2618    Tarzan (1999)',
 '1838    Mulan (1998)']

Давайте теперь построим рекомендации для юзеров

Как мы видим юзеру нравится фантастика, значит и в рекомендациях ожидаем увидеть фантастику

In [13]:
get_user_history = lambda user_id, implicit_ratings : [movie_info[movie_info["movie_id"] == x]["name"].to_string() 
                                            for x in implicit_ratings[implicit_ratings["user_id"] == user_id]["movie_id"]]

In [14]:
get_user_history(4, implicit_ratings)

['3399    Hustler, The (1961)',
 '2882    Fistful of Dollars, A (1964)',
 '1196    Alien (1979)',
 '1023    Die Hard (1988)',
 '257    Star Wars: Episode IV - A New Hope (1977)',
 '1959    Saving Private Ryan (1998)',
 '476    Jurassic Park (1993)',
 '1180    Raiders of the Lost Ark (1981)',
 '1885    Rocky (1976)',
 '1081    E.T. the Extra-Terrestrial (1982)',
 '3349    Thelma & Louise (1991)',
 '3633    Mad Max (1979)',
 '2297    King Kong (1933)',
 '1366    Jaws (1975)',
 '1183    Good, The Bad and The Ugly, The (1966)',
 '2623    Run Lola Run (Lola rennt) (1998)',
 '2878    Goldfinger (1964)',
 '1220    Terminator, The (1984)']

Получилось! 

Мы действительно порекомендовали пользователю фантастику и боевики, более того встречаются продолжения тех фильмов, которые он высоко оценил

In [15]:
get_recommendations = lambda user_id, model : [movie_info[movie_info["movie_id"] == x[0]]["name"].to_string() 
                                               for x in model.recommend(user_id, user_item_csr)]

In [16]:
get_recommendations(4, model)

['585    Terminator 2: Judgment Day (1991)',
 '1271    Indiana Jones and the Last Crusade (1989)',
 '2502    Matrix, The (1999)',
 '1182    Aliens (1986)',
 '1284    Butch Cassidy and the Sundance Kid (1969)',
 '1178    Star Wars: Episode V - The Empire Strikes Back...',
 '1179    Princess Bride, The (1987)',
 '847    Godfather, The (1972)',
 '1892    Rain Man (1988)',
 '3402    Close Encounters of the Third Kind (1977)']

ratings.movie_idТеперь ваша очередь реализовать самые популярные алгоритмы матричных разложений

Что будет оцениваться:
1. Корректность алгоритма
2. Качество получившихся симиларов
3. Качество итоговых рекомендаций для юзера

ratings### Задание 1. Не использую готовые решения, реализовать SVD разложение используя SGD на explicit данных

In [62]:
class SVD:
    def __init__(self, learning_rate = 1e-3, lambda_l2 = 1e-3, 
                 epsilon = 1e-3, latent_size = 16, max_iterations = int(1e7), verbose = int(1e5)):
        self.learning_rate = learning_rate
        self.lambda_l2 = lambda_l2
        self.epsilon = epsilon
        self.latent_size = latent_size
        self.max_iterations = max_iterations
        self.verbose = verbose 
        
    def fit(self, ratings, movie_info):
        # функция поиска описания фильма по его идентификатору
        self.search = lambda x: movie_info.loc[movie_info.movie_id == x]
        
        # инициализация матриц эмбедингов
        self.W = np.random.uniform(0, 1/np.sqrt(self.latent_size), 
                      size=(ratings.user_id.max(), self.latent_size)) 
        
        self.H = np.random.uniform(0, 1/np.sqrt(self.latent_size), 
                      size=(self.latent_size, ratings.movie_id.max())) 
        
        # инициализация векторов смещения
        self.Wb = np.random.normal(2.5, 0.5, ratings.user_id.max()).reshape(-1, 1) 
        self.Hb = np.random.normal(2.5, 0.5, ratings.movie_id.max()).reshape(1, -1) 
        self.mu = np.mean(ratings.rating.mean())
        
        ratings_numpy = ratings.to_numpy()
        self.movie_info = movie_info
        self.ratings = ratings
    
        l = ratings.shape[0]
        itx = 0
        
        while True:
            
            if not itx % self.verbose:
                # подсчет rmse на кратной итерации
                self.PR = np.array(self.W @ self.H + self.Wb + self.Hb + self.mu)
                idx_users = ratings_numpy[:, 0] - 1
                idx_movies = ratings_numpy[:, 1] - 1
                rvals = ratings_numpy[:, 2]
                f_norm =  np.linalg.norm(self.PR[idx_users, idx_movies] - rvals) / l
                print(f'|{itx}. rmse - {f_norm:.5f}')
                if f_norm <= self.epsilon:
                    break
                
            # градиентый спуск по случайному известному элементу матрицы рейтингов
            i, j, r = ratings_numpy[np.random.randint(l)]
            i -= 1
            j -= 1
            
            err = self.W[i, :] @ self.H[:, j] + self.Wb[i, :] + self.Hb[:, j] + self.mu - r
            
            W_upd = self.W[i, :] - self.learning_rate * (err * self.H[:, j].T + self.lambda_l2 * self.W[i, :])
            H_upd = self.H[:, j] - self.learning_rate * (err * self.W[i, :].T + self.lambda_l2 * self.H[:, j])
            
            
            self.Wb[i, :] -= self.learning_rate * (err + self.lambda_l2 * self.Wb[i, :])
            self.Hb[:, j] -= self.learning_rate * (err + self.lambda_l2 * self.Hb[:, j])
            
            self.W[i, :] = W_upd
            self.H[:, j] = H_upd
            
            itx += 1
            if itx >= self.max_iterations:
                break
        
        self.movie_values = self.ratings.movie_id.sort_values().unique()
        print(f'Done! ({itx}, {f_norm:.5f})')
        
    def history(self, idx, count = 5):
        # выгрузка истории просмотренных фильмов по идентификатору пользователя
        idies = self.ratings.loc[self.ratings.user_id == idx].sort_values('rating').movie_id.iloc[:count].values
        histories = pd.concat([self.search(i) for i in idies])
        return histories.to_numpy()
        

    def similar_items(self, idx, count = 5):
        # предсказание схожих по представлениям фильмов
        similar_key = lambda x: np.linalg.norm(self.H[:, x] - self.H[:, idx - 1])
        idx_movies_real = self.ratings.movie_id.sort_values().unique() 
        distances = [[x, np.linalg.norm(similar_key(x - 1))] for x in idx_movies_real]
        distances.sort(key = lambda x: x[1])
        idies = [i[0] for i in distances[:count + 1]]
        similaries = pd.concat([self.search(i) for i in idies])
        return similaries.to_numpy()
    
    def recommend(self, idx, count = 5):
        # рекомендации пользователю 
        user_ratings_all = np.array(self.W @ self.H + self.Wb + self.Hb + self.mu)[idx - 1]
        user_ratings = set(ratings.loc[ratings.user_id == idx].movie_id)
        sorted_all_idies = np.argsort(user_ratings_all)[::-1] + 1
        idies = [i for i in sorted_all_idies if i not in user_ratings][:count]
        recomendations = pd.concat([self.search(i) for i in idies])
        return recomendations.to_numpy()

In [63]:
SVD_SGD = SVD(learning_rate = 1e-2, lambda_l2 = 1e-5, latent_size = 64, epsilon = 1e-5, max_iterations = int(5e6), verbose = int(5e5))
SVD_SGD.fit(ratings, movie_info)

|0. rmse - 0.00543
|500000. rmse - 0.00129
|1000000. rmse - 0.00107
|1500000. rmse - 0.00100
|2000000. rmse - 0.00096
|2500000. rmse - 0.00094
|3000000. rmse - 0.00092
|3500000. rmse - 0.00091
|4000000. rmse - 0.00089
|4500000. rmse - 0.00087
Done! (5000000, 0.00087)


In [64]:
SVD_SGD.similar_items(1)

array([[1, 'Toy Story (1995)', "Animation|Children's|Comedy"],
       [3114, 'Toy Story 2 (1999)', "Animation|Children's|Comedy"],
       [595, 'Beauty and the Beast (1991)',
        "Animation|Children's|Musical"],
       [150, 'Apollo 13 (1995)', 'Drama'],
       [2078, 'Jungle Book, The (1967)',
        "Animation|Children's|Comedy|Musical"],
       [588, 'Aladdin (1992)', "Animation|Children's|Comedy|Musical"]],
      dtype=object)

In [65]:
SVD_SGD.recommend(4, 50)

array([[3561, "Stacy's Knights (1982)", 'Drama'],
       [2199, 'Phoenix (1998)', 'Crime|Drama'],
       [1557, 'Squeeze (1996)', 'Drama'],
       [139, 'Target (1995)', 'Action|Drama'],
       [2319, 'Reach the Rock (1997)', 'Comedy'],
       [738, 'Garcu, Le (1995)', 'Drama'],
       [3356, 'Condo Painting (2000)', 'Documentary'],
       [1781, 'Further Gesture, A (1996)', 'Drama'],
       [721, 'Halfmoon (Paul Bowles - Halbmond) (1995)', 'Drama'],
       [1158, 'Here Comes Cookie (1935)', 'Comedy'],
       [3380, 'Railroaded! (1947)', 'Film-Noir'],
       [2217, 'Elstree Calling (1930)', 'Comedy|Musical'],
       [713, 'Of Love and Shadows (1994)', 'Drama'],
       [2218, 'Juno and Paycock (1930)', 'Drama'],
       [795, 'Somebody to Love (1994)', 'Drama'],
       [1852, 'Love Walked In (1998)', 'Drama|Thriller'],
       [857, 'Crows and Sparrows (1949)', 'Drama'],
       [624, 'Condition Red (1995)', 'Action|Drama|Thriller'],
       [773, 'Touki Bouki (Journey of the Hyena) (1973)'

In [66]:
SVD_SGD.history(4, 50)

array([[3527, 'Predator (1987)', 'Action|Sci-Fi|Thriller'],
       [1196, 'Star Wars: Episode V - The Empire Strikes Back (1980)',
        'Action|Adventure|Drama|Sci-Fi|War'],
       [1210, 'Star Wars: Episode VI - Return of the Jedi (1983)',
        'Action|Adventure|Romance|Sci-Fi|War'],
       [2951, 'Fistful of Dollars, A (1964)', 'Action|Western'],
       [1214, 'Alien (1979)', 'Action|Horror|Sci-Fi|Thriller'],
       [1036, 'Die Hard (1988)', 'Action|Thriller'],
       [480, 'Jurassic Park (1993)', 'Action|Adventure|Sci-Fi'],
       [1097, 'E.T. the Extra-Terrestrial (1982)',
        "Children's|Drama|Fantasy|Sci-Fi"],
       [3418, 'Thelma & Louise (1991)', 'Action|Drama'],
       [3702, 'Mad Max (1979)', 'Action|Sci-Fi'],
       [2366, 'King Kong (1933)', 'Action|Adventure|Horror'],
       [3468, 'Hustler, The (1961)', 'Drama'],
       [2692, 'Run Lola Run (Lola rennt) (1998)', 'Action|Crime|Romance'],
       [1201, 'Good, The Bad and The Ugly, The (1966)', 'Action|Western'],


### Задание 2. Не использую готовые решения, реализовать матричное разложение используя ALS на implicit данных

In [25]:
class ALS:
    def __init__(self, learning_rate = 1e-3, lambda_l2 = 1e-3, 
                 epsilon = 1e-3, latent_size = 16, max_iterations = int(1e7), verbose = int(1e5)):
        self.learning_rate = learning_rate
        self.lambda_l2 = lambda_l2
        self.epsilon = epsilon
        self.latent_size = latent_size
        self.max_iterations = max_iterations
        self.verbose = verbose 
        
    def fit(self, ratings, movie_info):
        self.search = lambda x: movie_info.loc[movie_info.movie_id == x]
        
        self.W = np.random.uniform(0, 1/np.sqrt(self.latent_size), 
                      size=(ratings.user_id.max(), self.latent_size)) 
        
        self.H = np.random.uniform(0, 1/np.sqrt(self.latent_size), 
                      size=(self.latent_size, ratings.movie_id.max()))     
        
        ratings_numpy = ratings.to_numpy()
        
        u_id = ratings_numpy[:, 0] - 1
        m_id = ratings_numpy[:, 1] - 1
        r_vl = ratings_numpy[:, 2]
        
        self.movie_info = movie_info
        self.ratings = ratings
    
        l = ratings.shape[0]
        itx = 0
        
        while True:
            self.PR = np.array(self.W @ self.H)
            if not itx % self.verbose:
                idx_users = ratings_numpy[:, 0] - 1
                idx_movies = ratings_numpy[:, 1] - 1
                rvals = ratings_numpy[:, 2]
                f_norm =  np.linalg.norm(self.PR[idx_users, idx_movies] - rvals) / l
                print(f'|{itx}. rmse - {f_norm:.5f}')
                if f_norm <= self.epsilon:
                    break
                    
            err = dp(self.PR)
            err[u_id, m_id] -= r_vl
            
            if not itx % 2:
                self.W -= self.learning_rate * (err @ self.H.T + self.lambda_l2 * self.W)
            else:
                self.H -= self.learning_rate * (self.W.T @ err + self.lambda_l2 * self.H)
            
            itx += 1
            if itx >= self.max_iterations:
                break
        
        self.movie_values = self.ratings.movie_id.sort_values().unique()
        print(f'Done! ({itx}, {f_norm:.5f})')
        
    def history(self, idx, count = 5):
        # выгрузка истории просмотренных фильмов по идентификатору пользователя
        idies = self.ratings.loc[self.ratings.user_id == idx].sort_values('rating').movie_id.iloc[:count].values
        histories = pd.concat([self.search(i) for i in idies])
        return histories.to_numpy()
        

    def similar_items(self, idx, count = 5):
        # предсказание схожих по представлениям фильмов
        similar_key = lambda x: np.linalg.norm(self.H[:, x] - self.H[:, idx - 1])
        idx_movies_real = self.ratings.movie_id.sort_values().unique() 
        distances = [[x, np.linalg.norm(similar_key(x - 1))] for x in idx_movies_real]
        distances.sort(key = lambda x: x[1])
        idies = [i[0] for i in distances[:count + 1]]
        similaries = pd.concat([self.search(i) for i in idies])
        return similaries.to_numpy()
    
    def recommend(self, idx, count = 5):
        # рекомендации пользователю 
        user_ratings_all = np.array(self.W @ self.H)[idx - 1]
        user_ratings = set(ratings.loc[ratings.user_id == idx].movie_id)
        sorted_all_idies = np.argsort(user_ratings_all)[::-1] + 1
        idies = [i for i in sorted_all_idies if i not in user_ratings][:count]
        recomendations = pd.concat([self.search(i) for i in idies])
        return recomendations.to_numpy()

In [26]:
ALS_SGD = ALS(learning_rate = 1e-3, lambda_l2 = 1e-3, latent_size = 64, epsilon = 1e-4, max_iterations = 150, verbose = 25)
ALS_SGD.fit(implicit_ratings, movie_info)

|0. rmse - 0.00550
|25. rmse - 0.00439
|50. rmse - 0.00395
|75. rmse - 0.00374
|100. rmse - 0.00370
|125. rmse - 0.00369
Done! (150, 0.00369)


In [27]:
ALS_SGD.similar_items(1)

array([[1, 'Toy Story (1995)', "Animation|Children's|Comedy"],
       [3114, 'Toy Story 2 (1999)', "Animation|Children's|Comedy"],
       [2355, "Bug's Life, A (1998)", "Animation|Children's|Comedy"],
       [588, 'Aladdin (1992)', "Animation|Children's|Comedy|Musical"],
       [364, 'Lion King, The (1994)', "Animation|Children's|Musical"],
       [2321, 'Pleasantville (1998)', 'Comedy']], dtype=object)

In [32]:
ALS_SGD.recommend(4, 20)

array([[1291, 'Indiana Jones and the Last Crusade (1989)',
        'Action|Adventure'],
       [1200, 'Aliens (1986)', 'Action|Sci-Fi|Thriller|War'],
       [1304, 'Butch Cassidy and the Sundance Kid (1969)',
        'Action|Comedy|Western'],
       [457, 'Fugitive, The (1993)', 'Action|Thriller'],
       [589, 'Terminator 2: Judgment Day (1991)',
        'Action|Sci-Fi|Thriller'],
       [2529, 'Planet of the Apes (1968)', 'Action|Sci-Fi'],
       [2571, 'Matrix, The (1999)', 'Action|Sci-Fi|Thriller'],
       [3471, 'Close Encounters of the Third Kind (1977)',
        'Drama|Sci-Fi'],
       [858, 'Godfather, The (1972)', 'Action|Crime|Drama'],
       [110, 'Braveheart (1995)', 'Action|Drama|War'],
       [1197, 'Princess Bride, The (1987)',
        'Action|Adventure|Comedy|Romance'],
       [2000, 'Lethal Weapon (1987)', 'Action|Comedy|Crime|Drama'],
       [969, 'African Queen, The (1951)', 'Action|Adventure|Romance|War'],
       [1953, 'French Connection, The (1971)',
        'Acti

In [33]:
ALS_SGD.history(4, 20)

array([[2951, 'Fistful of Dollars, A (1964)', 'Action|Western'],
       [1214, 'Alien (1979)', 'Action|Horror|Sci-Fi|Thriller'],
       [1036, 'Die Hard (1988)', 'Action|Thriller'],
       [480, 'Jurassic Park (1993)', 'Action|Adventure|Sci-Fi'],
       [2366, 'King Kong (1933)', 'Action|Adventure|Horror'],
       [1097, 'E.T. the Extra-Terrestrial (1982)',
        "Children's|Drama|Fantasy|Sci-Fi"],
       [3418, 'Thelma & Louise (1991)', 'Action|Drama'],
       [3702, 'Mad Max (1979)', 'Action|Sci-Fi'],
       [3468, 'Hustler, The (1961)', 'Drama'],
       [2692, 'Run Lola Run (Lola rennt) (1998)', 'Action|Crime|Romance'],
       [1201, 'Good, The Bad and The Ugly, The (1966)', 'Action|Western'],
       [1387, 'Jaws (1975)', 'Action|Horror'],
       [1954, 'Rocky (1976)', 'Action|Drama'],
       [1198, 'Raiders of the Lost Ark (1981)', 'Action|Adventure'],
       [2028, 'Saving Private Ryan (1998)', 'Action|Drama|War'],
       [260, 'Star Wars: Episode IV - A New Hope (1977)',
      

### Задание 3. Не использую готовые решения, реализовать матричное разложение BPR на implicit данных

In [17]:
class PosNeg:
    def __init__(self, positive, negative):
        self.pos = positive
        self.neg = negative
        
    def sample(self):
        for pos in self.pos:
            for neg in np.random.choice(self.neg, 7):
                yield (pos, neg)
        

class BPR:
    def __init__(self, learning_rate = 1e-3, lambda_l2 = 1e-3, 
                 epsilon = 1e-3, latent_size = 16, max_iterations = int(1e7), verbose = int(1e5)):
        self.learning_rate = learning_rate
        self.lambda_l2 = lambda_l2
        self.epsilon = epsilon
        self.latent_size = latent_size
        self.max_iterations = max_iterations
        self.verbose = verbose 
        
    def fit(self, ratings, movie_info):
        
        
        # функция поиска описания фильма по его идентификатору
        self.search = lambda x: movie_info.loc[movie_info.movie_id == x]
        
        # инициализация матриц эмбедингов
        self.W = np.random.uniform(0, 1/np.sqrt(self.latent_size), 
                      size=(ratings.user_id.max(), self.latent_size)) 
        
        self.H = np.random.uniform(0, 1/np.sqrt(self.latent_size), 
                      size=(self.latent_size, ratings.movie_id.max())) 
        set_movies_all = set(ratings.movie_id.unique())
        
        ratings_numpy = ratings.to_numpy()
        self.movie_info = movie_info
        self.ratings = ratings
    
        l = ratings.shape[0]
        itx = 0
        
        samples = {}
        set_movies_all = set(ratings.movie_id.unique())
        for u_pos in tqdm(ratings.user_id.unique(), position = 0, leave = False, desc = 'preprocessing'):
            u_movies = ratings.loc[ratings.user_id == u_pos].movie_id
            set_movies_pos = set(u_movies)
            set_movies_neg = set_movies_all - set_movies_pos
            samples[u_pos] = PosNeg(list(set_movies_pos),
                                    list(set_movies_neg))
        
        while True:

            self.PR = np.array(self.W @ self.H)
            idx_users = ratings_numpy[:, 0] - 1
            idx_movies = ratings_numpy[:, 1] - 1
            rvals = ratings_numpy[:, 2]
            f_norm =  np.linalg.norm(self.PR[idx_users, idx_movies] - rvals) / l
            if f_norm <= self.epsilon:
                break
                    
            for u_pos in tqdm(ratings.user_id.unique(), position=0, leave=False, desc=f'|{itx}. rmse - {f_norm:.10f}'):
                u_pos = u_pos - 1
                for m_pos, m_neg in samples[u_pos + 1].sample():
                    m_pos = m_pos - 1
                    m_neg = m_neg - 1

                    # считаем расстояние от позитивного отзыва до негативного
                    r_pos = self.W[u_pos, :] @ self.H[:, m_pos]# + self.biasV[m_pos]
                    r_neg = self.W[u_pos, :] @ self.H[:, m_neg]# + self.biasV[m_neg]
                    err = r_pos - r_neg

                    loss = 1.0 / (1 + np.exp(err))
                    self.W[u_pos, :] += self.learning_rate * (loss * (self.H[:, m_pos].T - self.H[:, m_neg].T)
                                                          - self.lambda_l2 * self.W[u_pos, :])

                    self.H[:, m_pos] += self.learning_rate * (loss * self.W[u_pos, :].T - self.lambda_l2 * self.H[:, m_pos])
                    self.H[:, m_neg] += self.learning_rate * (loss * -self.W[u_pos, :].T - self.lambda_l2 * self.H[:, m_neg])
                        
            itx += 1
            if itx >= self.max_iterations:
                break
        
        self.movie_values = self.ratings.movie_id.sort_values().unique()
        print(f'Done! ({itx}, {f_norm:.5f})')
        
    def history(self, idx, count = 5):
        # выгрузка истории просмотренных фильмов по идентификатору пользователя
        idies = self.ratings.loc[self.ratings.user_id == idx].sort_values('rating').movie_id.iloc[:count].values
        histories = pd.concat([self.search(i) for i in idies])
        return histories.to_numpy()
        

    def similar_items(self, idx, count = 5):
        # предсказание схожих по представлениям фильмов
        similar_key = lambda x: np.linalg.norm(self.H[:, x] - self.H[:, idx - 1])
        idx_movies_real = self.ratings.movie_id.sort_values().unique() 
        distances = [[x, np.linalg.norm(similar_key(x - 1))] for x in idx_movies_real]
        distances.sort(key = lambda x: x[1])
        idies = [i[0] for i in distances[:count + 1]]
        similaries = pd.concat([self.search(i) for i in idies])
        return similaries.to_numpy()
    
    def recommend(self, idx, count = 5):
        # рекомендации пользователю 
        user_ratings_all = np.array(self.W @ self.H)[idx - 1]
        user_ratings = set(ratings.loc[ratings.user_id == idx].movie_id)
        sorted_all_idies = np.argsort(user_ratings_all)[::-1] + 1
        idies = [i for i in sorted_all_idies if i not in user_ratings][:count]
        recomendations = pd.concat([self.search(i) for i in idies])
        return recomendations.to_numpy()

In [18]:
BPR_SGD = BPR(learning_rate = 1e-2, lambda_l2 = 1e-4, latent_size = 64, epsilon = 1e-4, max_iterations = 6, verbose = 1)
BPR_SGD.fit(implicit_ratings, movie_info)

Done! (6, 0.00224)


In [19]:
BPR_SGD.similar_items(1)

array([[1, 'Toy Story (1995)', "Animation|Children's|Comedy"],
       [3114, 'Toy Story 2 (1999)', "Animation|Children's|Comedy"],
       [1265, 'Groundhog Day (1993)', 'Comedy|Romance'],
       [2355, "Bug's Life, A (1998)", "Animation|Children's|Comedy"],
       [34, 'Babe (1995)', "Children's|Comedy|Drama"],
       [1197, 'Princess Bride, The (1987)',
        'Action|Adventure|Comedy|Romance']], dtype=object)

In [20]:
BPR_SGD.history(4, 20)

array([[2951, 'Fistful of Dollars, A (1964)', 'Action|Western'],
       [1214, 'Alien (1979)', 'Action|Horror|Sci-Fi|Thriller'],
       [1036, 'Die Hard (1988)', 'Action|Thriller'],
       [480, 'Jurassic Park (1993)', 'Action|Adventure|Sci-Fi'],
       [2366, 'King Kong (1933)', 'Action|Adventure|Horror'],
       [1097, 'E.T. the Extra-Terrestrial (1982)',
        "Children's|Drama|Fantasy|Sci-Fi"],
       [3418, 'Thelma & Louise (1991)', 'Action|Drama'],
       [3702, 'Mad Max (1979)', 'Action|Sci-Fi'],
       [3468, 'Hustler, The (1961)', 'Drama'],
       [2692, 'Run Lola Run (Lola rennt) (1998)', 'Action|Crime|Romance'],
       [1201, 'Good, The Bad and The Ugly, The (1966)', 'Action|Western'],
       [1387, 'Jaws (1975)', 'Action|Horror'],
       [1954, 'Rocky (1976)', 'Action|Drama'],
       [1198, 'Raiders of the Lost Ark (1981)', 'Action|Adventure'],
       [2028, 'Saving Private Ryan (1998)', 'Action|Drama|War'],
       [260, 'Star Wars: Episode IV - A New Hope (1977)',
      

In [21]:
BPR_SGD.recommend(4, 20)

array([[858, 'Godfather, The (1972)', 'Action|Crime|Drama'],
       [2571, 'Matrix, The (1999)', 'Action|Sci-Fi|Thriller'],
       [2858, 'American Beauty (1999)', 'Comedy|Drama'],
       [589, 'Terminator 2: Judgment Day (1991)',
        'Action|Sci-Fi|Thriller'],
       [593, 'Silence of the Lambs, The (1991)', 'Drama|Thriller'],
       [541, 'Blade Runner (1982)', 'Film-Noir|Sci-Fi'],
       [1200, 'Aliens (1986)', 'Action|Sci-Fi|Thriller|War'],
       [608, 'Fargo (1996)', 'Crime|Drama|Thriller'],
       [1617, 'L.A. Confidential (1997)',
        'Crime|Film-Noir|Mystery|Thriller'],
       [2762, 'Sixth Sense, The (1999)', 'Thriller'],
       [1197, 'Princess Bride, The (1987)',
        'Action|Adventure|Comedy|Romance'],
       [296, 'Pulp Fiction (1994)', 'Crime|Drama'],
       [110, 'Braveheart (1995)', 'Action|Drama|War'],
       [1221, 'Godfather: Part II, The (1974)', 'Action|Crime|Drama'],
       [527, "Schindler's List (1993)", 'Drama|War'],
       [924, '2001: A Space Odys

### Задание 4. Не использую готовые решения, реализовать матричное разложение WARP на implicit данных

In [45]:
class PosNeg:
    def __init__(self, positive, negative):
        self.pos = positive
        self.neg = negative
        

class WARP:
    def __init__(self, learning_rate = 1e-3, lambda_l2 = 1e-3, 
                 epsilon = 1e-3, latent_size = 16, max_iterations = int(1e7), verbose = int(1e5)):
        self.learning_rate = learning_rate
        self.lambda_l2 = lambda_l2
        self.epsilon = epsilon
        self.latent_size = latent_size
        self.max_iterations = max_iterations
        self.verbose = verbose 
        
    def fit(self, ratings, movie_info):
        
        
        # функция поиска описания фильма по его идентификатору
        self.search = lambda x: movie_info.loc[movie_info.movie_id == x]
        
        # инициализация матриц эмбедингов
        self.W = np.random.uniform(0, 1/np.sqrt(self.latent_size), 
                      size=(ratings.user_id.max(), self.latent_size)) 
        
        self.H = np.random.uniform(0, 1/np.sqrt(self.latent_size), 
                      size=(self.latent_size, ratings.movie_id.max())) 
        set_movies_all = set(ratings.movie_id.unique())
        
        ratings_numpy = ratings.to_numpy()
        self.movie_info = movie_info
        self.ratings = ratings
    
        l = ratings.shape[0]
        itx = 0
        
        samples = {}
        set_movies_all = set(ratings.movie_id.unique())
        for u_pos in tqdm(ratings.user_id.unique(), position = 0, leave = False, desc = 'preprocessing'):
            u_movies = ratings.loc[ratings.user_id == u_pos].movie_id
            set_movies_pos = set(u_movies)
            set_movies_neg = set_movies_all - set_movies_pos
            samples[u_pos] = PosNeg(list(set_movies_pos),
                                    list(set_movies_neg))
        
        while True:

            self.PR = np.array(self.W @ self.H)
            idx_users = ratings_numpy[:, 0] - 1
            idx_movies = ratings_numpy[:, 1] - 1
            rvals = ratings_numpy[:, 2]
            f_norm =  np.linalg.norm(self.PR[idx_users, idx_movies] - rvals) / l
            if f_norm <= self.epsilon:
                break
                    
            for u_pos in tqdm(ratings.user_id.unique(), position=0, leave=False, desc=f'|{itx}. rmse - {f_norm:.10f}'):
                u_pos = u_pos - 1
                # проходимся по всем позитивным примерам пользователя
                for m_pos in samples[u_pos + 1].pos:
                    # инициализируем счетчик
                    counter = 1
                    # семплируем негативные примеры
                    for m_neg in np.random.choice(samples[u_pos + 1].neg, 15):
                        m_pos = m_pos - 1
                        m_neg = m_neg - 1

                        # считаем рейтинг негативного и позитивного примеров
                        r_pos = self.W[u_pos, :] @ self.H[:, m_pos]
                        r_neg = self.W[u_pos, :] @ self.H[:, m_neg]
                        
                        if r_neg + 1 > r_pos:
                            loss = np.log(15/counter)
                            self.W[u_pos, :] += self.learning_rate * (loss * (self.H[:, m_pos].T - self.H[:, m_neg].T)
                                                              - self.lambda_l2 * self.W[u_pos, :])

                            self.H[:, m_pos] += self.learning_rate * (loss * self.W[u_pos, :].T - self.lambda_l2 * self.H[:, m_pos])
                            self.H[:, m_neg] += self.learning_rate * (loss * -self.W[u_pos, :].T - self.lambda_l2 * self.H[:, m_neg])
                            break
 
                        counter += 1
                        
            itx += 1
            if itx >= self.max_iterations:
                break
        
        self.movie_values = self.ratings.movie_id.sort_values().unique()
        print(f'Done! ({itx}, {f_norm:.5f})')
        
    def history(self, idx, count = 5):
        # выгрузка истории просмотренных фильмов по идентификатору пользователя
        idies = self.ratings.loc[self.ratings.user_id == idx].sort_values('rating').movie_id.iloc[:count].values
        histories = pd.concat([self.search(i) for i in idies])
        return histories.to_numpy()
        

    def similar_items(self, idx, count = 5):
        # предсказание схожих по представлениям фильмов
        similar_key = lambda x: np.linalg.norm(self.H[:, x] - self.H[:, idx - 1])
        idx_movies_real = self.ratings.movie_id.sort_values().unique() 
        distances = [[x, np.linalg.norm(similar_key(x - 1))] for x in idx_movies_real]
        distances.sort(key = lambda x: x[1])
        idies = [i[0] for i in distances[:count + 1]]
        similaries = pd.concat([self.search(i) for i in idies])
        return similaries.to_numpy()
    
    def recommend(self, idx, count = 5):
        # рекомендации пользователю 
        user_ratings_all = np.array(self.W @ self.H)[idx - 1]
        user_ratings = set(ratings.loc[ratings.user_id == idx].movie_id)
        sorted_all_idies = np.argsort(user_ratings_all)[::-1] + 1
        idies = [i for i in sorted_all_idies if i not in user_ratings][:count]
        recomendations = pd.concat([self.search(i) for i in idies])
        return recomendations.to_numpy()

In [46]:
WARP_SGD = WARP(learning_rate = 1e-2, lambda_l2 = 1e-5, latent_size = 64, epsilon = 1e-4, max_iterations = 15, verbose = 1)
WARP_SGD.fit(implicit_ratings, movie_info)

Done! (15, 0.00300)


In [51]:
WARP_SGD.similar_items(1, 20)

array([[1, 'Toy Story (1995)', "Animation|Children's|Comedy"],
       [3951, 'Two Family House (2000)', 'Drama'],
       [3952, 'Contender, The (2000)', 'Drama|Thriller'],
       [3950, 'Tigerland (2000)', 'Drama'],
       [3112, "'Night Mother (1986)", 'Drama'],
       [3949, 'Requiem for a Dream (2000)', 'Drama'],
       [3113, 'End of Days (1999)', 'Action|Thriller'],
       [3111, 'Places in the Heart (1984)', 'Drama'],
       [3114, 'Toy Story 2 (1999)', "Animation|Children's|Comedy"],
       [3110, 'Country (1984)', 'Drama'],
       [2294, 'Antz (1998)', "Animation|Children's"],
       [2293, 'Shadrach (1998)', 'Drama'],
       [3109, 'River, The (1984)', 'Drama'],
       [1144, 'Line King: Al Hirschfeld, The (1996)', 'Documentary'],
       [2292, 'Overnight Delivery (1996)', 'Romance'],
       [2320, 'Apt Pupil (1998)', 'Drama|Thriller'],
       [1588, 'George of the Jungle (1997)', "Children's|Comedy"],
       [659, 'Purple Noon (1960)', 'Crime|Thriller'],
       [360, 'I Love 

In [54]:
WARP_SGD.history(4, 20)

array([[2951, 'Fistful of Dollars, A (1964)', 'Action|Western'],
       [1214, 'Alien (1979)', 'Action|Horror|Sci-Fi|Thriller'],
       [1036, 'Die Hard (1988)', 'Action|Thriller'],
       [480, 'Jurassic Park (1993)', 'Action|Adventure|Sci-Fi'],
       [2366, 'King Kong (1933)', 'Action|Adventure|Horror'],
       [1097, 'E.T. the Extra-Terrestrial (1982)',
        "Children's|Drama|Fantasy|Sci-Fi"],
       [3418, 'Thelma & Louise (1991)', 'Action|Drama'],
       [3702, 'Mad Max (1979)', 'Action|Sci-Fi'],
       [3468, 'Hustler, The (1961)', 'Drama'],
       [2692, 'Run Lola Run (Lola rennt) (1998)', 'Action|Crime|Romance'],
       [1201, 'Good, The Bad and The Ugly, The (1966)', 'Action|Western'],
       [1387, 'Jaws (1975)', 'Action|Horror'],
       [1954, 'Rocky (1976)', 'Action|Drama'],
       [1198, 'Raiders of the Lost Ark (1981)', 'Action|Adventure'],
       [2028, 'Saving Private Ryan (1998)', 'Action|Drama|War'],
       [260, 'Star Wars: Episode IV - A New Hope (1977)',
      

In [55]:
WARP_SGD.recommend(4, 20)

array([[1035, 'Sound of Music, The (1965)', 'Musical'],
       [589, 'Terminator 2: Judgment Day (1991)',
        'Action|Sci-Fi|Thriller'],
       [259, 'Kiss of Death (1995)', 'Crime|Drama|Thriller'],
       [1953, 'French Connection, The (1971)',
        'Action|Crime|Drama|Thriller'],
       [110, 'Braveheart (1995)', 'Action|Drama|War'],
       [592, 'Batman (1989)', 'Action|Adventure|Crime|Drama'],
       [109, 'Headless Body in Topless Bar (1995)', 'Comedy'],
       [258, "Kid in King Arthur's Court, A (1995)",
        "Adventure|Children's|Comedy|Fantasy|Romance"],
       [1952, 'Midnight Cowboy (1969)', 'Drama'],
       [108, 'Catwalk (1995)', 'Documentary'],
       [857, 'Crows and Sparrows (1949)', 'Drama'],
       [1034, 'Freeway (1996)', 'Crime'],
       [1386, 'Terror in a Texas Town (1958)', 'Western'],
       [1385, 'Under Siege (1992)', 'Action'],
       [1200, 'Aliens (1986)', 'Action|Sci-Fi|Thriller|War'],
       [591, 'Tough and Deadly (1995)', 'Action|Drama|Thrille